name: Deploy TanStack Start to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Project Dependencies
        run: npm install

      - name: Static Compile for GitHub Pages
        run: npx vinxi build

      - name: Upload Static Web Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.output/public'

      - name: Deploy Live to Pages
        id: deployment
        uses: actions/deploy-pages@v4
